Resolve missing apt dependency via postBuild.sh (#6)
`binder` run raised:
```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Stackoverflow suggestion: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo